#7 Fix UI blink for passive key
hCaptcha/react-native-hcaptcha pull request #8
Opened 2022-01-13 18:54 UTC by CAMOBAP

1. the fix, proposed in https://github.com/hCaptcha/react-native-hcaptcha/issues/7#issuecomment-996946369 works
2. I have verified the fix with `0.63.4`

### Issues
3. Yesterday I faced with JCenter down issue https://status.gradle.com/
4. Example contains `RangeError: Maximum call stack size exceeded.` loop between `onMessage -> hide -> onMessage -> ...` (screenshot attached). But this error is invisible in production mode only during debug

### Open question
5. Should I continue the investigation on 4
6. I still have some issues with the 0.66.1 version, @e271828- could you please update your local example to confirm this issue, also I need to know if this important

2022-01-13 23:30 UTC, e271828- commented
> 1. the fix, proposed in [Webview fades on / off for passive sitekey #7 (comment)](https://github.com/hCaptcha/react-native-hcaptcha/issues/7#issuecomment-996946369) works
> 2. I have verified the fix with `0.63.4`
> 
> ### Issues
> 3. Yesterday I faced with JCenter down issue https://status.gradle.com/
> 4. Example contains `RangeError: Maximum call stack size exceeded.` loop between `onMessage -> hide -> onMessage -> ...` (screenshot attached). But this error is invisible in production mode only during debug <img alt="" width="250" src="https://user-images.githubusercontent.com/2169738/149409858-3e31f51c-46d6-409c-8f6b-bda73d98a541.png">
> 
> ### Open question
> 5. Should I continue the investigation on 4

Yep.

> 6. I still have some issues with the 0.66.1 version, @e271828- could you please update your local example to confirm this issue, also I need to know if this important

Please try to fix for yourself locally, will take a look if that fails.

> 7. Is there a reason why https://github.com/react-native-modal/react-native-modal used instead `import { Modal } from "react-native";`?

Probably for some convenience API like dismiss-on-background-click, don't recall for sure.

> 8. I think it makes sense to do some integration testing with `react-native init && yarn add file:..` just to check that compilation works

+1

2022-01-13 23:31 UTC, e271828- requested changes
I think this requires a switch like "passive=true" (quick/ugly fix) or a different approach, e.g. unhide modal if visible challenge is presented, as determined by open callback firing.

2022-01-14 06:34 UTC, CAMOBAP commented
> I think this requires a switch like "passive=true" (quick/ugly fix) or a different approach, e.g. unhide modal if visible challenge is presented, as determined by open callback firing.

I wanted to ask the same) BTW there is no way to check if a key is passive (maybe it have some prefix or specific pattern)?

2022-01-14 16:27 UTC, e271828- commented
> > I think this requires a switch like "passive=true" (quick/ugly fix) or a different approach, e.g. unhide modal if visible challenge is presented, as determined by open callback firing.
> 
> I wanted to ask the same) BTW there is no way to check if a key is passive (maybe it have some prefix or specific pattern)?

There is no way, and some will be mixed. The open callback is your only option there.

2022-01-14 16:45 UTC, CAMOBAP commented
> > > I think this requires a switch like "passive=true" (quick/ugly fix) or a different approach, e.g. unhide modal if visible challenge is presented, as determined by open callback firing.
> > 
> > 
> > I wanted to ask the same) BTW there is no way to check if a key is passive (maybe it have some prefix or specific pattern)?
> 
> There is no way, and some will be mixed. The open callback is your only option there.

Ok I will add `passiveSiteKey` option which will be `false` by default, but if `true` passed it will apply these changes

2022-01-14 22:04 UTC, CAMOBAP commented
Done

2022-01-15 11:44 UTC, e271828- commented on MAINTAINER.md
> +`yarn` starts and never finisehd during last module install like this
```suggestion
`yarn` starts but never finishes during last module install like this
```

2022-01-15 11:48 UTC, merged